baseURL = 'https://n0rbb.github.io/'
languageCode = 'es-es'
title = 'Norbb'
theme = 'DigitalGarden' 

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
[[menu.main]]
  name = 'Principal'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Contenido'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Registro'
  url = '/posts'
  weight = 3
[[menu.main]]
  name = 'Notas de viaje'
  url = '/notas_de_viaje'
  weight = 4
